import { Organization, Project, Task, User, NotificationItem, Membership, Invitation } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alex Chen',
    email: 'alex.chen@acme.io',
    avatar: '/src/assets/images/avatar_alex_chen_1791022586358.jpg',
    initials: 'AC',
    role: 'Owner',
    title: 'VP of Engineering',
    joinedAt: '2024-01-15T00:00:00.000Z',
    twoFactorEnabled: true,
  },
  {
    id: 'user-2',
    name: 'Marcus Vance',
    email: 'marcus.v@acme.io',
    initials: 'MV',
    role: 'Admin',
    title: 'Staff Product Designer',
    joinedAt: '2024-03-02T00:00:00.000Z',
    twoFactorEnabled: true,
  },
  {
    id: 'user-3',
    name: 'Elena Rostova',
    email: 'elena.r@acme.io',
    initials: 'ER',
    role: 'Admin',
    title: 'Principal Architect',
    joinedAt: '2024-04-19T00:00:00.000Z',
    twoFactorEnabled: true,
  },
  {
    id: 'user-4',
    name: 'David Kim',
    email: 'david.k@acme.io',
    initials: 'DK',
    role: 'Member',
    title: 'Senior Backend Engineer',
    joinedAt: '2024-07-24T00:00:00.000Z',
    twoFactorEnabled: false,
  },
  {
    id: 'user-5',
    name: 'Maya Patel',
    email: 'maya.p@acme.io',
    initials: 'MP',
    role: 'Member',
    title: 'Frontend Developer',
    joinedAt: '2024-08-11T00:00:00.000Z',
    twoFactorEnabled: true,
  },
  {
    id: 'user-6',
    name: 'Liam O\'Connor',
    email: 'liam.oc@acme.io',
    initials: 'LO',
    role: 'Member',
    title: 'Technical Product Manager',
    joinedAt: '2024-11-05T00:00:00.000Z',
    twoFactorEnabled: true,
  },
];

export const mockOrganizations: Organization[] = [
  {
    id: 'org-1',
    name: 'Acme Technologies',
    slug: 'acme-tech',
    plan: 'Enterprise',
    timezone: 'Africa/Lagos',
    currentRole: 'Owner',
    membersCount: 24,
  },
  {
    id: 'org-2',
    name: 'Starlight AI Labs',
    slug: 'starlight-ai',
    plan: 'Growth',
    timezone: 'America/New_York',
    currentRole: 'Admin',
    membersCount: 12,
  },
  {
    id: 'org-3',
    name: 'Hyperion Design Studio',
    slug: 'hyperion-studio',
    plan: 'Starter',
    timezone: 'Europe/London',
    currentRole: 'Member',
    membersCount: 6,
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    orgId: 'org-1',
    name: 'Cloud Infrastructure V2',
    key: 'CLD',
    description: 'Migration to multi-region Kubernetes clusters with automated zero-downtime canary rollouts.',
    color: '#3B82F6',
    leadId: 'user-1',
    status: 'active',
    dueDate: '2026-10-25',
    createdAt: '2026-08-10T09:00:00.000Z',
    memberIds: ['user-1', 'user-3', 'user-4'],
  },
  {
    id: 'proj-2',
    orgId: 'org-1',
    name: 'Mobile App Redesign',
    key: 'MOB',
    description: 'Native iOS and Android client refresh focused on offline task synchronization and sub-100ms transitions.',
    color: '#8B5CF6',
    leadId: 'user-2',
    status: 'active',
    dueDate: '2026-11-15',
    createdAt: '2026-09-01T10:30:00.000Z',
    memberIds: ['user-2', 'user-5', 'user-6'],
  },
  {
    id: 'proj-3',
    orgId: 'org-1',
    name: 'Zero-Trust Security Mesh',
    key: 'SEC',
    description: 'Enforcing mTLS across internal microservices and auditing SOC2 Type II compliance controls.',
    color: '#10B981',
    leadId: 'user-3',
    status: 'active',
    dueDate: '2026-10-18',
    createdAt: '2026-07-20T14:15:00.000Z',
    memberIds: ['user-3', 'user-1', 'user-4'],
  },
  {
    id: 'proj-4',
    orgId: 'org-1',
    name: 'Self-Serve Billing Portal',
    key: 'BIL',
    description: 'Usage-based metering integration with Stripe webhooks and automated tax deduction invoices.',
    color: '#F59E0B',
    leadId: 'user-6',
    status: 'active',
    dueDate: '2026-12-05',
    createdAt: '2026-09-12T11:00:00.000Z',
    memberIds: ['user-6', 'user-4', 'user-5'],
  },
  {
    id: 'proj-5',
    orgId: 'org-2',
    name: 'Model Fine-tuning Pipeline',
    key: 'FTN',
    description: 'Distributed training orchestration for domain-adapted tokenizers and quantized models.',
    color: '#EC4899',
    leadId: 'user-1',
    status: 'active',
    dueDate: '2026-11-30',
    createdAt: '2026-09-05T08:00:00.000Z',
    memberIds: ['user-1', 'user-3'],
  },
];

export const mockTasks: Task[] = [
  // Cloud Infrastructure Tasks (CLD)
  {
    id: 'task-1',
    key: 'CLD-101',
    projectId: 'proj-1',
    orgId: 'org-1',
    title: 'Migrate ingress controller to Envoy Gateway 1.2',
    description: 'Update the cluster ingress configuration to leverage Envoy Gateway API for dynamic traffic splitting and weighted canary routing.',
    status: 'TODO',
    priority: 'high',
    assigneeId: 'user-3',
    createdById: 'user-1',
    position: 0,
    dueDate: '2026-10-08',
    tags: ['DevOps', 'Kubernetes'],
    createdAt: '2026-09-28T09:12:00.000Z',
    attachments: [
      {
        id: 'att-1',
        orgId: 'org-1',
        taskId: 'task-1',
        name: 'envoy-gateway-topology.pdf',
        size: '1.4 MB',
        type: 'application/pdf',
        uploadedAt: '2026-10-01T14:30:00.000Z',
        uploaderName: 'Elena Rostova',
      },
      {
        id: 'att-2',
        orgId: 'org-1',
        taskId: 'task-1',
        name: 'benchmark-traffic-metrics.csv',
        size: '420 KB',
        type: 'text/csv',
        uploadedAt: '2026-10-02T10:00:00.000Z',
        uploaderName: 'Elena Rostova',
      },
    ],
    comments: [
      {
        id: 'comm-1',
        orgId: 'org-1',
        taskId: 'task-1',
        authorId: 'user-1',
        authorName: 'Alex Chen',
        authorAvatar: '/src/assets/images/avatar_alex_chen_1791022586358.jpg',
        authorInitials: 'AC',
        content: 'Please ensure we have fallback DNS routes tested in staging first before touching prod clusters.',
        createdAt: '2026-10-02T15:45:00.000Z',
      },
      {
        id: 'comm-2',
        orgId: 'org-1',
        taskId: 'task-1',
        authorId: 'user-3',
        authorName: 'Elena Rostova',
        authorInitials: 'ER',
        content: 'Already scheduled the staging sandbox verification window for tomorrow morning at 09:00 UTC.',
        createdAt: '2026-10-03T09:15:00.000Z',
      },
    ],
  },
  {
    id: 'task-2',
    key: 'CLD-102',
    projectId: 'proj-1',
    orgId: 'org-1',
    title: 'Configure Prometheus Alertmanager escalation matrices',
    description: 'Define pager duty notification routes for CPU saturation >85% persisting over 5 minutes and 5xx rate spikes.',
    status: 'TODO',
    priority: 'medium',
    assigneeId: 'user-4',
    createdById: 'user-1',
    position: 1,
    dueDate: '2026-10-12',
    tags: ['Monitoring', 'SRE'],
    createdAt: '2026-09-29T11:00:00.000Z',
    attachments: [],
    comments: [],
  },
  {
    id: 'task-3',
    key: 'CLD-103',
    projectId: 'proj-1',
    orgId: 'org-1',
    title: 'Optimize Redis cache cluster eviction policies',
    description: 'Switch key eviction policy to volatile-lfu and benchmark throughput under 25,000 requests per second peak load.',
    status: 'IN_PROGRESS',
    priority: 'urgent',
    assigneeId: 'user-1',
    createdById: 'user-1',
    position: 0,
    dueDate: '2026-10-04',
    tags: ['Performance', 'Database'],
    createdAt: '2026-09-27T16:20:00.000Z',
    attachments: [
      {
        id: 'att-3',
        orgId: 'org-1',
        taskId: 'task-3',
        name: 'redis-memory-profile.png',
        size: '890 KB',
        type: 'image/png',
        uploadedAt: '2026-09-30T12:00:00.000Z',
        uploaderName: 'Alex Chen',
      },
    ],
    comments: [
      {
        id: 'comm-3',
        orgId: 'org-1',
        taskId: 'task-3',
        authorId: 'user-4',
        authorName: 'David Kim',
        authorInitials: 'DK',
        content: 'I observed a 14% latency reduction in the test cluster after tuning maxmemory-samples to 10.',
        createdAt: '2026-10-03T01:00:00.000Z',
      },
    ],
  },
  {
    id: 'task-4',
    key: 'CLD-104',
    projectId: 'proj-1',
    orgId: 'org-1',
    title: 'Implement Terraform state locking via DynamoDB',
    description: 'Ensure cross-team concurrent infrastructure deployments do not corrupt state files during CI execution.',
    status: 'IN_PROGRESS',
    priority: 'high',
    assigneeId: 'user-4',
    createdById: 'user-1',
    position: 1,
    dueDate: '2026-10-09',
    tags: ['Infrastructure', 'Terraform'],
    createdAt: '2026-09-30T10:00:00.000Z',
    attachments: [],
    comments: [],
  },
  {
    id: 'task-5',
    key: 'CLD-105',
    projectId: 'proj-1',
    orgId: 'org-1',
    title: 'Automated database snapshot backup script validation',
    description: 'Test cold recovery drills from multi-region encrypted S3 snapshot buckets to prove RTO < 30 minutes.',
    status: 'DONE',
    priority: 'medium',
    assigneeId: 'user-3',
    createdById: 'user-3',
    position: 0,
    dueDate: '2026-10-01',
    tags: ['Security', 'Backup'],
    createdAt: '2026-09-20T14:00:00.000Z',
    attachments: [
      {
        id: 'att-4',
        orgId: 'org-1',
        taskId: 'task-5',
        name: 'rto-verification-signoff.pdf',
        size: '620 KB',
        type: 'application/pdf',
        uploadedAt: '2026-09-30T18:00:00.000Z',
        uploaderName: 'Elena Rostova',
      },
    ],
    comments: [
      {
        id: 'comm-4',
        orgId: 'org-1',
        taskId: 'task-5',
        authorId: 'user-1',
        authorName: 'Alex Chen',
        authorAvatar: '/src/assets/images/avatar_alex_chen_1791022586358.jpg',
        authorInitials: 'AC',
        content: 'Verification passed with 18m 42s recovery time! Great job team.',
        createdAt: '2026-09-30T16:20:00.000Z',
      },
    ],
  },
  {
    id: 'task-6',
    key: 'CLD-106',
    projectId: 'proj-1',
    orgId: 'org-1',
    title: 'Upgrade EKS nodes to Bottlerocket OS release v1.19',
    description: 'Minimize host OS footprint and reduce surface vulnerability vectors across compute pools.',
    status: 'DONE',
    priority: 'low',
    assigneeId: 'user-1',
    createdById: 'user-3',
    position: 1,
    dueDate: '2026-09-28',
    tags: ['Security', 'Kubernetes'],
    createdAt: '2026-09-18T08:00:00.000Z',
    attachments: [],
    comments: [],
  },

  // Mobile App Redesign Tasks (MOB)
  {
    id: 'task-7',
    key: 'MOB-201',
    projectId: 'proj-2',
    orgId: 'org-1',
    title: 'Design high-fidelity dark mode navigation tokens',
    description: 'Create semantic design tokens in Figma for border contrast, subtle active states, and WCAG AAA compliance.',
    status: 'TODO',
    priority: 'high',
    assigneeId: 'user-2',
    createdById: 'user-2',
    position: 0,
    dueDate: '2026-10-10',
    tags: ['Design', 'UI/UX'],
    createdAt: '2026-10-01T15:00:00.000Z',
    attachments: [
      {
        id: 'att-5',
        orgId: 'org-1',
        taskId: 'task-7',
        name: 'navigation-tokens-v2.fig',
        size: '3.8 MB',
        type: 'application/octet-stream',
        uploadedAt: '2026-10-02T16:00:00.000Z',
        uploaderName: 'Marcus Vance',
      },
    ],
    comments: [],
  },
  {
    id: 'task-8',
    key: 'MOB-202',
    projectId: 'proj-2',
    orgId: 'org-1',
    title: 'Build offline SQLite synchronization queue',
    description: 'Store mutations locally when disconnected and replay via exponential backoff upon network reconnection.',
    status: 'IN_PROGRESS',
    priority: 'urgent',
    assigneeId: 'user-5',
    createdById: 'user-2',
    position: 0,
    dueDate: '2026-10-07',
    tags: ['Mobile', 'Offline'],
    createdAt: '2026-09-29T13:00:00.000Z',
    attachments: [],
    comments: [],
  },
  {
    id: 'task-9',
    key: 'MOB-203',
    projectId: 'proj-2',
    orgId: 'org-1',
    title: 'Haptic feedback integration for board drag operations',
    description: 'Implement CoreHaptics on iOS and VibratorManager on Android when picking up and snapping cards into columns.',
    status: 'DONE',
    priority: 'medium',
    assigneeId: 'user-5',
    createdById: 'user-5',
    position: 0,
    dueDate: '2026-09-29',
    tags: ['Mobile', 'Polish'],
    createdAt: '2026-09-22T10:00:00.000Z',
    attachments: [],
    comments: [],
  },

  // Zero-Trust Security Mesh Tasks (SEC)
  {
    id: 'task-10',
    key: 'SEC-301',
    projectId: 'proj-3',
    orgId: 'org-1',
    title: 'Audit SPIFFE/SPIRE workload identity attestation',
    description: 'Verify cryptographic SVID rotation happens automatically within the 1-hour validity window.',
    status: 'TODO',
    priority: 'urgent',
    assigneeId: 'user-3',
    createdById: 'user-3',
    position: 0,
    dueDate: '2026-10-05',
    tags: ['Security', 'Compliance'],
    createdAt: '2026-09-27T08:30:00.000Z',
    attachments: [],
    comments: [],
  },
  {
    id: 'task-11',
    key: 'SEC-302',
    projectId: 'proj-3',
    orgId: 'org-1',
    title: 'Penetration test report remediation for OAuth callback',
    description: 'Enforce strict PKCE and state parameter nonce validation against open redirect attacks.',
    status: 'DONE',
    priority: 'high',
    assigneeId: 'user-4',
    createdById: 'user-3',
    position: 0,
    dueDate: '2026-09-26',
    tags: ['Security', 'Auth'],
    createdAt: '2026-09-15T12:00:00.000Z',
    attachments: [],
    comments: [],
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    orgId: 'org-1',
    title: 'Elena mentioned you',
    description: 'In task CLD-101: "Please ensure we have fallback DNS routes tested in staging first..."',
    timestamp: '15m ago',
    read: false,
    type: 'mention',
    projectId: 'proj-1',
    taskId: 'task-1',
  },
  {
    id: 'notif-2',
    orgId: 'org-1',
    title: 'Task due soon',
    description: 'CLD-103 "Optimize Redis cache cluster eviction policies" is due tomorrow.',
    timestamp: '1h ago',
    read: false,
    type: 'deadline',
    projectId: 'proj-1',
    taskId: 'task-3',
  },
  {
    id: 'notif-3',
    orgId: 'org-1',
    title: 'Marcus assigned you a task',
    description: 'You were assigned to MOB-201: Design high-fidelity dark mode navigation tokens.',
    timestamp: '3h ago',
    read: false,
    type: 'assignment',
    projectId: 'proj-2',
    taskId: 'task-7',
  },
  {
    id: 'notif-4',
    orgId: 'org-1',
    title: 'New member joined Acme Technologies',
    description: 'Liam O\'Connor joined the organization as Member.',
    timestamp: 'Yesterday',
    read: true,
    type: 'team',
  },
  {
    id: 'notif-5',
    orgId: 'org-1',
    title: 'Project milestone reached',
    description: 'Cloud Infrastructure V2 reached 33% task completion velocity.',
    timestamp: '2 days ago',
    read: true,
    type: 'deadline',
    projectId: 'proj-1',
  },
];

export const mockMemberships: Membership[] = [
  {
    id: 'tm-1',
    orgId: 'org-1',
    user: mockUsers[0],
    role: 'Owner',
    joinedDate: '2024-01-15T00:00:00.000Z',
    status: 'active',
  },
  {
    id: 'tm-2',
    orgId: 'org-1',
    user: mockUsers[1],
    role: 'Admin',
    joinedDate: '2024-03-02T00:00:00.000Z',
    status: 'active',
  },
  {
    id: 'tm-3',
    orgId: 'org-1',
    user: mockUsers[2],
    role: 'Admin',
    joinedDate: '2024-04-19T00:00:00.000Z',
    status: 'active',
  },
  {
    id: 'tm-4',
    orgId: 'org-1',
    user: mockUsers[3],
    role: 'Member',
    joinedDate: '2024-07-24T00:00:00.000Z',
    status: 'active',
  },
  {
    id: 'tm-5',
    orgId: 'org-1',
    user: mockUsers[4],
    role: 'Member',
    joinedDate: '2024-08-11T00:00:00.000Z',
    status: 'active',
  },
  {
    id: 'tm-6',
    orgId: 'org-1',
    user: mockUsers[5],
    role: 'Member',
    joinedDate: '2024-11-05T00:00:00.000Z',
    status: 'active',
  },
];

export const mockInvitations: Invitation[] = [
  {
    id: 'inv-1',
    orgId: 'org-1',
    email: 'sarah.engineer@acme.io',
    role: 'Member',
    token: 'tok-acme-inv-1',
    expiresAt: '2026-10-15T00:00:00.000Z',
    acceptedAt: null,
  },
];
